var officerList = [
	{
	"name": "Jimmy Eskew",
	"role": "President",
	"image": "./img/placeholder.png",
	"insta": "",
	"linkedin": "",
	},
	{
	"name": "Vanessa Huynh",
	"role": "VP of Internal Affairs",
	"image": "./img/placeholder.png",
	"insta": "https://www.instagram.com/v_hnh/",
	"linkedin": "https://www.linkedin.com/in/vanessahuynh0/",
	},
	{
	"name": "Hotaru Garcia",
	"role": "VP of Programs",
	"image": "./img/placeholder.png",
	"insta": "https://instagram.com/theeluminessence/",
	"linkedin": "https://www.linkedin.com/in/lumine-garc%C3%ADa-b70b6921b",
	},
	{
	"name": "Aka Alaragi",
	"role": "Director of Operations",
	"image": "./img/placeholder.png",
	"insta": "",
	"linkedin": "",
	},
	{
	"name": "Jverlyn Brown",
	"role": "Historian",
	"image": "./img/placeholder.png",
	"insta": "",
	"linkedin": "",
	},
	{
	"name": "Lauren Meagher",
	"role": "Communications",
	"image": "./img/placeholder.png",
	"insta": "",
	"linkedin": "",
	},
	{
	"name": "Riley Johnston",
	"role": "Designer",
	"image": "./img/placeholder.png",
	"insta": "",
	"linkedin": "",
	},
	{
	"name": "Ajay Pandher",
	"role": "Event Coordinator",
	"image": "./img/placeholder.png",
	"insta": "",
	"linkedin": "",
	},
	{
	"name": "Miguel Trejo",
	"role": "Treasurer",
	"image": "./img/placeholder.png",
	"insta": "",
	"linkedin": "",
	},
];