var officerList = [
	{
	"name": "Jimmy Eskew",
	"role": "President",
	"image": "./img/officers/Jimmy.png",
	"insta": "https://www.instagram.com/jimmy.eskew/",
	"linkedin": "",
	},
	{
	"name": "Vanessa Huynh",
	"role": "VP of Internal Affairs",
	"image": "./img/officers/Vanessa.png",
	"insta": "https://www.instagram.com/v_hnh/",
	"linkedin": "https://www.linkedin.com/in/vanessahuynh0/",
	},
	{
	"name": "Hotaru Garcia",
	"role": "VP of Programs",
	"image": "./img/officers/Hotaru.png",
	"insta": "https://instagram.com/theeluminessence/",
	"linkedin": "https://www.linkedin.com/in/lumine-garc%C3%ADa-b70b6921b",
	},
	{
	"name": "Aka Alaragi",
	"role": "Director of Operations",
	"image": "./img/officers/Aka.png",
	"insta": "",
	"linkedin": "https://www.linkedin.com/in/aka-sarah-al-7b4705232",
	},
	{
	"name": "Jverlyn Brown",
	"role": "Historian",
	"image": "./img/officers/Jverlyn.png",
	"insta": "https://www.instagram.com/jverly.n/",
	"linkedin": "",
	},
	{
	"name": "Lauren Meagher",
	"role": "Communications",
	"image": "./img/officers/Lauren.png",
	"insta": "https://www.instagram.com/laurensuzuki_/",
	"linkedin": "",
	},
	{
	"name": "Riley Johnston",
	"role": "Designer",
	"image": "./img/officers/placeholder.png",
	"insta": "https://www.instagram.com/rileygracej/",
	"linkedin": "",
	},
	{
	"name": "Ajay Pandher",
	"role": "Event Coordinator",
	"image": "./img/officers/Ajay.png",
	"insta": "https://www.instagram.com/th3drak0n3/",
	"linkedin": "",
	},
	{
	"name": "Miguel Trejo",
	"role": "Treasurer",
	"image": "./img/officers/Miguel.png",
	"insta": "",
	"linkedin": "",
	},
];